CREATE TABLE PROJECTS (
  ID SERIAL PRIMARY KEY,
  NOME VARCHAR(255),
  IMG_URL VARCHAR(255),
  URL VARCHAR(255),
  REPO VARCHAR(255),
  STATUS VARCHAR(1),
  STACK VARCHAR(255)
);

CREATE TABLE TIMELINE (
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(255),
  DESCRIPTION VARCHAR(255),
  YEAR INTEGER(4),
  DURATION VARCHAR(50),
  STATUS VARCHAR(1)
);

CREATE TABLE POST (
    ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(255),
    RESUME VARCHAR(800),
    CONTENT VARCHAR(8000),
    PUBLISHED BOOLEAN NOT NULL DEFAULT false,
    AUTHOR VARCHAR(30),
    CREATED_AT TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CONTACT (
  ID SERIAL PRIMARY KEY,
  NOME VARCHAR(255),
  DESCRIPTION VARCHAR(255),
  ADDRESS VARCHAR(255),
  IMG VARCHAR(255),
  STATUS VARCHAR(1)
);

CREATE TABLE TECH (
  ID SERIAL PRIMARY KEY,
  NOME VARCHAR(255)
);

CREATE TABLE STACK (
  ID SERIAL PRIMARY KEY,
  PROJECTS_ID INT,
  TECH_ID INT,

  CONSTRAINT PROJECT_STACK
    FOREIGN KEY(PROJECTS_ID)
      REFERENCES PROJECTS(ID)

  CONSTRAINT STACK_TECH
    FOREIGN KEY(TECH_ID)
      REFERENCES TECH(ID)
);